#!/bin/bash

ws=`i3-msg -t get_workspaces | jq '.[] | select(.focused==true).name' | cut -d"\"" -f2`

i3-msg "workspace 1; append_layout ~/.config/i3/workspaces/workspace-1.json"
kitty --name term1 &
code-oss &
kitty --name dev_server &
kitty --name venv &
kitty --name term2 &

i3-msg "workspace 9; exec discord"

i3-msg "workspace 10; append_layout ~/.config/i3/workspaces/workspace-10.json"
chromium &
firefox &